// NOTE: Comments that start with [AI] were generated by GitHub Copilot (AI helper).

// In-memory data storage
// [AI] `tourismData` will hold cleaned records from the CSV after parsing.
let tourismData = [];
// [AI] `losChart` keeps a reference to the Chart.js chart so we can destroy/rebuild it safely.
let losChart = null;

// [AI] CSV file includes some footer/metadata lines that are not real data.
// [AI] If a row contains one of these phrases in `Group`, we ignore that row.
const SKIP_KEYWORDS = ['Data is updated', 'Source of Data', 'Seasonally adjusted', 'Hotel performance'];

// [AI] Cache important DOM elements once so we can reuse them everywhere.
const losForm = document.getElementById('losForm');
const categorySelect = document.getElementById('category');
const locationSelect = document.getElementById('location');
const loadingDiv = document.getElementById('loading');
const errorDiv = document.getElementById('error');
const resultsDiv = document.getElementById('results');

// [AI] Load the CSV file and kick off parsing + UI setup.
async function loadCSVData() {
    try {
        showLoading();

        // [AI] 1) Download the raw CSV text from the same folder.
        const response = await fetch('data.csv');
        const csvText = await response.text();

        // [AI] 2) Parse CSV text into an array of row objects using Papa Parse.
        Papa.parse(csvText, {
            header: true,
            complete: function(results) {
            // [AI] 3) Clean/transform parsed rows and build dropdowns.
                processData(results.data);
                populateDropdowns();
                hideLoading();
            },
            error: function(error) {
                showError('Error parsing CSV: ' + error.message);
                hideLoading();
            }
        });
    } catch (error) {
        showError('Error loading CSV file: ' + error.message);
        hideLoading();
    }
}

// [AI] Convert raw CSV rows into the app's internal shape.
function processData(data) {
    tourismData = [];

    data.forEach(row => {
        const group = row.Group || '';

        // [AI] Skip footer/metadata rows and empty rows.
        if (!group || SKIP_KEYWORDS.some(keyword => group.includes(keyword))) {
            return;
        }

        const indicator = row.Indicator || '';
        const units = row.Units || 'days';

        // [AI] Extract year columns only (e.g., 1999, 2000, ...).
        // [AI] For each year, keep only valid numeric values.
        const yearlyData = [];
        Object.keys(row).forEach(key => {
            if (!isNaN(key) && row[key] && row[key].trim() !== '') {
                const value = parseFloat(row[key]);
                if (!isNaN(value)) {
                    yearlyData.push({
                        year: key,
                        value: value
                    });
                }
            }
        });

        if (yearlyData.length > 0) {
            // [AI] Store one normalized record for easier filtering/stat calculations later.
            tourismData.push({
                group,
                indicator,
                units,
                yearlyData
            });
        }
    });

    console.log(`Loaded ${tourismData.length} records`);
}

// [AI] Fill dropdown menus from unique values found in loaded data.
function populateDropdowns() {
    // Get unique categories and locations
    const categories = [...new Set(tourismData.map(d => d.group))].sort();
    const locations = [...new Set(tourismData.map(d => d.indicator))].sort();

    // Populate category dropdown
    categorySelect.innerHTML = '<option value="">-- Select Category --</option>';
    categories.forEach(category => {
        const option = document.createElement('option');
        option.value = category;
        option.textContent = category;
        categorySelect.appendChild(option);
    });

    // Populate location dropdown
    locationSelect.innerHTML = '<option value="">-- All Locations --</option>';
    locations.forEach(location => {
        const option = document.createElement('option');
        option.value = location;
        option.textContent = location;
        locationSelect.appendChild(option);
    });
}

// [AI] When user clicks "Calculate", validate inputs and compute results.
function handleFormSubmit(e) {
    e.preventDefault();

    const category = categorySelect.value;
    const location = locationSelect.value;

    if (!category) {
        showError('Please select a category');
        return;
    }

    hideError();
    hideResults();

    try {
        const results = calculateLOS(category, location);
        displayResults(results);
    } catch (error) {
        showError('Error calculating results: ' + error.message);
    }
}

// [AI] Core business logic:
// [AI] 1) Filter records by selected category/location.
// [AI] 2) Flatten all year/value points.
// [AI] 3) Calculate summary stats + chart series.
function calculateLOS(category, location) {
    // [AI] Filter records by selected category.
    let filtered = tourismData.filter(record => record.group === category);

    if (location) {
        // [AI] If a location was selected, narrow further.
        filtered = filtered.filter(record => record.indicator === location);
    }

    if (filtered.length === 0) {
        throw new Error('No data found for the specified criteria');
    }

    // [AI] Collect all year/value points from filtered records into one array.
    const allValues = [];
    filtered.forEach(record => {
        record.yearlyData.forEach(yearData => {
            allValues.push({
                year: yearData.year,
                value: yearData.value,
                location: record.indicator
            });
        });
    });

    if (allValues.length === 0) {
        throw new Error('No valid data points found');
    }

    // [AI] Compute summary statistics.
    const values = allValues.map(v => v.value);
    const sum = values.reduce((a, b) => a + b, 0);
    const average = sum / values.length;
    const min = Math.min(...values);
    const max = Math.max(...values);

    const minEntry = allValues.find(v => v.value === min);
    const maxEntry = allValues.find(v => v.value === max);

    // [AI] Build year -> [values] map, then convert to year -> average for chart.
    const yearlyAverages = {};
    allValues.forEach(item => {
        if (!yearlyAverages[item.year]) {
            yearlyAverages[item.year] = [];
        }
        yearlyAverages[item.year].push(item.value);
    });

    const chartData = Object.keys(yearlyAverages).sort().map(year => ({
        year,
        average: yearlyAverages[year].reduce((a, b) => a + b, 0) / yearlyAverages[year].length
    }));

    return {
        category,
        location: location || 'All locations',
        statistics: {
            average: parseFloat(average.toFixed(2)),
            min: {
                value: min,
                year: minEntry.year,
                location: minEntry.location
            },
            max: {
                value: max,
                year: maxEntry.year,
                location: maxEntry.location
            },
            dataPoints: values.length
        },
        chartData
    };
}

// [AI] Put computed results into the HTML.
function displayResults(data) {
    document.getElementById('resultCategory').textContent = data.category;
    document.getElementById('resultLocation').textContent = data.location;

    const stats = data.statistics;
    document.getElementById('avgValue').textContent = stats.average.toFixed(2);
    document.getElementById('minValue').textContent = stats.min.value.toFixed(2);
    document.getElementById('minDetail').textContent = `${stats.min.year} - ${stats.min.location}`;
    document.getElementById('maxValue').textContent = stats.max.value.toFixed(2);
    document.getElementById('maxDetail').textContent = `${stats.max.year} - ${stats.max.location}`;
    document.getElementById('dataPoints').textContent = stats.dataPoints;

    createChart(data.chartData);
    showResults();
}

// [AI] Draw (or redraw) the line chart with Chart.js.
function createChart(chartData) {
    const ctx = document.getElementById('losChart').getContext('2d');

    // [AI] Destroy previous chart instance to prevent duplicates/memory leaks.
    if (losChart) {
        losChart.destroy();
    }

    const labels = chartData.map(d => d.year);
    const values = chartData.map(d => d.average);

    losChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: labels,
            datasets: [{
                label: 'Average Length of Stay (days)',
                data: values,
                borderColor: '#667eea',
                backgroundColor: 'rgba(102, 126, 234, 0.1)',
                borderWidth: 3,
                fill: true,
                tension: 0.4,
                pointRadius: 4,
                pointHoverRadius: 6,
                pointBackgroundColor: '#667eea',
                pointBorderColor: '#fff',
                pointBorderWidth: 2
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: true,
            plugins: {
                legend: {
                    display: true,
                    position: 'top',
                },
                tooltip: {
                    mode: 'index',
                    intersect: false,
                    callbacks: {
                        label: function(context) {
                            return 'Average: ' + context.parsed.y.toFixed(2) + ' days';
                        }
                    }
                }
            },
            scales: {
                y: {
                    beginAtZero: false,
                    title: {
                        display: true,
                        text: 'Days'
                    },
                    ticks: {
                        callback: function(value) {
                            return value.toFixed(1);
                        }
                    }
                },
                x: {
                    title: {
                        display: true,
                        text: 'Year'
                    }
                }
            },
            interaction: {
                mode: 'nearest',
                axis: 'x',
                intersect: false
            }
        }
    });
}

// [AI] UI helper functions: show/hide loading, errors, and result section.
function showLoading() {
    loadingDiv.style.display = 'block';
}

function hideLoading() {
    loadingDiv.style.display = 'none';
}

function showError(message) {
    errorDiv.textContent = message;
    errorDiv.style.display = 'block';
}

function hideError() {
    errorDiv.style.display = 'none';
}

function showResults() {
    resultsDiv.style.display = 'block';
    resultsDiv.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
}

function hideResults() {
    resultsDiv.style.display = 'none';
}

// [AI] Reset button should clear messages and hide previous results.
function handleFormReset() {
    hideError();
    hideResults();
}

// [AI] Wire up form events.
losForm.addEventListener('submit', handleFormSubmit);
losForm.addEventListener('reset', handleFormReset);

// [AI] App startup: load CSV immediately when page opens.
loadCSVData();
